version: "3"

services:
    db:
        image: postgres
        container_name: db
        restart: always
        env_file:
            - server/.env.prod
        ports:
            - 3333:5432
        volumes:
            - pg:/var/lib/postgresql/data
        networks:
            - app_network

    node_app:
        container_name: node_app
        build: ./server/
        env_file:
            - server/.env.prod
        ports:
            - 5000:5000
        depends_on:
            - db
        networks:
            - app_network

    app_vue:
        container_name: "app_vue"
        build: ./web
        env_file: web/.env.prod
        volumes:
            - build_vue:/var/www/html

    nginx:
        build: ./nginx
        container_name: nginx
        ports:
            - 80:80
        volumes:
            - build_vue:/var/www/html
        depends_on:
            - app_vue
            - node_app
        networks:
            - app_network

volumes:
    build_vue:
    pg:

networks:
    app_network:
        driver: bridge
