version: "3"

services:
    db:
        image: postgres
        container_name: db
        restart: always
        env_file:
            - ./.env
        ports:
            - 3333:5432
        networks:
            - app_network

    node_app:
        container_name: node_app
        build: ./server/
        env_file:
            - ./.env
        ports:
            - 5000:5000
        command: ["npm", "run", "test:e2e:ci"]
        depends_on:
            - db
        networks:
            - app_network

networks:
    app_network:
        driver: bridge
